project:
  title: "AlgorithmicRecourseDynamics.jl"
  execute-dir: project
bibliography: bib.bib

crossref:
  fig-prefix: Figure
  tbl-prefix: Table
fig-format: png

execute: 
  freeze: auto
  eval: true
  echo: true
  output: false

jupyter: julia-1.8



