[".DS_Store"]
git-tree-sha1 = "3a6b8f6ee7c4e1d5101de4b253420ef1793ee955"
lazy = true

    [[".DS_Store".download]]
    sha256 = "25e5cb2210faa13cdc9bdbb8d7fa9df7e996c8ca909843ce9ddbf46f289e701d"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/.DS_Store.tar.gz"

[data]
git-tree-sha1 = "6a7708ecfcadafeca45a665a77172b2c24b6be8e"
lazy = true

    [[data.download]]
    sha256 = "8aa2aceefa771558c4fe3354594a006654dab5309c46c1b977b4125c1930bbb8"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/data.tar.gz"

[output]
git-tree-sha1 = "98f9df190de40f5fe3f0c3005ca1ce2692a29268"
lazy = true

    [[output.download]]
    sha256 = "466c2afcd3a2e0892b834ad57d7a65f35127a474ff13c5fe6dc0abff13419a5c"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/output.tar.gz"

[www]
git-tree-sha1 = "300f69c0176b1b69e137fac1b1751c21e1cff54e"
lazy = true

    [[www.download]]
    sha256 = "285392620edf878afdc085e886d116a6dfb4d70d265117a33dbb49e5f96e11f0"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/www.tar.gz"
