[".DS_Store"]
git-tree-sha1 = "fd85941fd7f29a346972b61686f46d58c26abe2d"
lazy = true

    [[".DS_Store".download]]
    sha256 = "e0350c23c2407210e28364a189d9b4e3f828cd2db4114cede9a663b2614f8559"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/.DS_Store.tar.gz"

[data]
git-tree-sha1 = "d0d63c39e075b025db47c26deb6aa9eb20b79f7d"
lazy = true

    [[data.download]]
    sha256 = "3fd96c6a93937c7ea5f775ae033937ffe94fe8c8594f4f0a441d0ccba77ddc86"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/data.tar.gz"

[output]
git-tree-sha1 = "f4dcbdcaa2bb8868a89b2df750d3561ebeb5fe93"
lazy = true

    [[output.download]]
    sha256 = "295611102b0d174c0474b3f63979e22775d96a5132091fdfc59bb8cf50e71776"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/output.tar.gz"

[www]
git-tree-sha1 = "98b9510ccc5a4537df654f313bd265717c31dc7c"
lazy = true

    [[www.download]]
    sha256 = "567619c7114040742eac9aed0a913c8c464471347398b43122cb97f4670a6d1b"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/www.tar.gz"
