[".DS_Store"]
git-tree-sha1 = "47dc543f95ce1ab54d111b0b36ab1d05f7ba5d5e"
lazy = true

    [[".DS_Store".download]]
    sha256 = "d2510068e2290acf1709a47e04611861e58a45a5922a6a1dd3aa866d356efa2b"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/.DS_Store.tar.gz"

[data]
git-tree-sha1 = "d7734dd821c36bc181f575b46f6afb394497393f"
lazy = true

    [[data.download]]
    sha256 = "73efadb77cf38b7811e2aac2ab01b2a67da4cf04418063c3d57725a18a7ccefc"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/data.tar.gz"

[output]
git-tree-sha1 = "e25df1a3511e490be373a468edad4b31f09fdf1e"
lazy = true

    [[output.download]]
    sha256 = "82eaea65141cdbd91d184a97bc9b6b5292d14ea51e75ef0438e3b7a712451ffe"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/output.tar.gz"

[www]
git-tree-sha1 = "6f4d5eac4c2b8d83ede7fee343d9c95496a5484b"
lazy = true

    [[www.download]]
    sha256 = "476a4e75400199f3b095a0050d4a28b0cfc8c6f52483c5a362fa81716f9c65b7"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/www.tar.gz"
