[".DS_Store"]
git-tree-sha1 = "add37026d90f9dc85ee316fbf083020cb6f2954a"
lazy = true

    [[".DS_Store".download]]
    sha256 = "b94ae5fc3980606903d7f0cc1e251897c19aca736b77d160d539bca2e36ac6f8"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/.DS_Store.tar.gz"

[data]
git-tree-sha1 = "bd13f13fbe6d7d17f3ef4c00e50d4eb090f360b3"
lazy = true

    [[data.download]]
    sha256 = "578d845c4f40d557d89fe6718984e6fe8db8ffa8b2dd31a4a67f91f0b18c74e3"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/data.tar.gz"

[output]
git-tree-sha1 = "98f9df190de40f5fe3f0c3005ca1ce2692a29268"
lazy = true

    [[output.download]]
    sha256 = "4a8695053c3c5df3aab0c6da12a679e44c8f96d784307c73b3a57a8acc17bfae"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/output.tar.gz"

[www]
git-tree-sha1 = "58fb5fbf88c773303ce055bfd0c91fd8a5a90e10"
lazy = true

    [[www.download]]
    sha256 = "187dd841cd3e34d6b0970b12f6a961a2911284a6e0c71bf18e5ce7dba402c164"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/www.tar.gz"
