[".DS_Store"]
git-tree-sha1 = "e0ff0e63060f0d4eb061e727c24e6e5e4bcb4b2b"
lazy = true

    [[".DS_Store".download]]
    sha256 = "12306ceb726d19f382754055230d4760689925811dafb21bf6efe0fba2aca0fc"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/.DS_Store.tar.gz"

[data]
git-tree-sha1 = "e98ac538df7298dfb23d02fb24a1f7093bbe6191"
lazy = true

    [[data.download]]
    sha256 = "f530ebf3fb7101604bc68fdeb38c8694463a035e6df98f516deefee98dc5d295"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/data.tar.gz"

[output]
git-tree-sha1 = "b225f0190f290e4747d8e22615414fdc311f88cc"
lazy = true

    [[output.download]]
    sha256 = "29324b04d14dc898d270acbb22a1fae5290c55b4e955f86840d8fcfb85c19b38"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/output.tar.gz"

[www]
git-tree-sha1 = "58fb5fbf88c773303ce055bfd0c91fd8a5a90e10"
lazy = true

    [[www.download]]
    sha256 = "7530e3247b0432c65e20edacc2d83a8c8d5fb59367127421be6091d8134ade97"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/www.tar.gz"
