[".DS_Store"]
git-tree-sha1 = "2fcccf7122a7474bbad9e1c097c1e7f811a18588"
lazy = true

    [[".DS_Store".download]]
    sha256 = "4213d2ce458881ec7d26aaca08bf2ddeca84f0cc164418e80761545b132cd141"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/.DS_Store.tar.gz"

[data]
git-tree-sha1 = "f2f95078fb5e8e45024cea4e726f6d31db135d17"
lazy = true

    [[data.download]]
    sha256 = "fc109531db8ca9d34facdcab846ac9bcf9211b1c2af65d6027e91441a741b6ee"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/data.tar.gz"

[output]
git-tree-sha1 = "e58d7f0cd0a97939daf9b838475f6273bb66d915"
lazy = true

    [[output.download]]
    sha256 = "418c3267252a9e9544378199c7f65c092d7463204bcda7a5b6a2c60b5c1dfeab"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/output.tar.gz"

[www]
git-tree-sha1 = "58fb5fbf88c773303ce055bfd0c91fd8a5a90e10"
lazy = true

    [[www.download]]
    sha256 = "8ee9678107d505e815ed5553e78e2ace212bd521f11579916fec272ee696fd57"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/www.tar.gz"
