[".DS_Store"]
git-tree-sha1 = "e8426489a4c933b45fb31b6ae4349f4aa818348e"
lazy = true

    [[".DS_Store".download]]
    sha256 = "cfdad7a91e6b32a9415f6876edb7623333408fbc82d9f507db77fd64398c076a"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/.DS_Store.tar.gz"

[data]
git-tree-sha1 = "2dd05a2c999fc128934b0419a7b0d9f49cc2d406"
lazy = true

    [[data.download]]
    sha256 = "9c7c21da499c48490dedeb2857f90cb8438b7682900bef8ad47db8bed970c07c"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/data.tar.gz"

[output]
git-tree-sha1 = "caea2454bd7a3f0090e4dec01ea4423bb599a762"
lazy = true

    [[output.download]]
    sha256 = "0adb748bc8812fe106c2c1569483eb963505794b0f6a4180658ee06bd0d6dca2"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/output.tar.gz"

[www]
git-tree-sha1 = "98b9510ccc5a4537df654f313bd265717c31dc7c"
lazy = true

    [[www.download]]
    sha256 = "98d38a679bd03e3f9641fc23e62bcca7cdae0c2f71fba6be26958eef78f33526"
    url = "https://github.com/pat-alt/AlgorithmicRecourseDynamics.jl/releases/download/artifacts/www.tar.gz"
