---
title: "Data preprocessing"
author:
- "Patrick Altmeyer (p.altmeyer@tudelft.nl)"
date: "`r format(Sys.Date(), '%B, %Y')`"
output: 
  bookdown::pdf_document2: 
    toc: false
    includes:
      in_header: ../tex/preamble.tex
  bookdown::html_document2: default
fontsize: 12pt
bibliography: ../bib.bib
link-citations: true
abstract: "..."
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(
  echo = FALSE,
  warning=FALSE,
  message=FALSE,
  out.width = 450,
  fig.align = "center"
)
```

# German credit data

```{r}
library(data.table)
dat <- read.table("../data/raw/SouthGermanCredit/SouthGermanCredit.asc", header=TRUE) 
source("../data/raw/SouthGermanCredit/read_SouthGermanCredit.R") # apply preprocessing 
dt <- data.table(dat)
```

```{r}
library(mltools)
X_scm <- c("personal_status_sex", "age", "amount", "duration")
y <- "credit_risk"
vars <- c(y,X_scm)
dt_scm <- copy(dt[,.SD,.SDcols=vars])
dt_scm[,credit_risk:=as.numeric(credit_risk)-1] # turn into binary numerical
dt_scm <- one_hot(dt_scm) # one-hot encode personal_status_sex
setcolorder(dt_scm, c("credit_risk", "age", "amount", "duration"))
setnames(dt_scm, colnames(dt_scm), c("y", "x1", "x2", "x3", sprintf("i%i", 1:4)))
fwrite(dt_scm,"../data/credit.csv")
```

