---
title: "Endogenous Macrodynamics in Algorithmic Recourse"
affiliation:
  ## use one only of the following
  # author-columnar: true         ## one column per author
  institution-columnar: true  ## one column per institution (multiple autors eventually)
  # wide: true                  ## one column wide author/affiliation fields

  #author:   ## A custom author ordering field that breaks institution grouping.
  #  - name: Eldon Tyrell
  #    mark: 4
  #    email: eldon@starfleet-academy.star
  #  - name: Michael Shell
  #    mark: 1
  #  - name: Roy Batty
  #    mark: 4
  #    email: roy@replicant.offworld
  ## Authors cited in institution field are ignored when author field exists

  #author_multiline: ## Put authors in a given order, with multiline possibility. Authors cited in institution are ignored if exists
  #  - line:         ## Create a new author line
  #    - name: Michael Shell
  #      mark: 1
  #    - name: Homer Simpson
  #      mark: 2
  #      email: homer@thesimsons.com
  #    - name: Roy Batty
  #      mark: 4
  #      email: roy@replicant.offworld
  #  - line:         ## Create a second author line
  #    - name: Montgomery Scott
  #      mark: 3
  #    - name: Eldon Tyrell
  #      mark: 4

  institution:
    - name: |
        *Delft University of Technology*
      department: |
        *Faculty of Electrical Engineering, Mathematics and Computer Science*
      location: 2628 XE Delft, The Netherlands
      mark: 1
      author:
        - name: Patrick Altmeyer
          email: P.Altmeyer@tudelft.nl
        - name: Giovan Angela
          # email: G.J.A.Angela@student.tudelft.nl
        - name: Aleksander Buszydlik
          # email: A.J.Buszydlik@student.tudelft.nl
        - name: Karol Dobiczek
          # email: K.T.Dobiczek@student.tudelft.nl
        - name: Arie van Deursen
          # email: Arie.vanDeursen@tudelft.nl
        - name: Cynthia C. S. Liem
          # email: C.C.S.Liem@tudelft.nl
  #   - name: Twentieth Century Fox
  #     location: Springfield, USA
  #     mark: 2
  #     author:
  #       - name: Homer Simpson
  #         email: homer@thesimpsons.com
  #   - name: Starfleet Academy
  #     location: San Francisco, California 96678-2391
  #     other: "Telephone: (800) 555--1212, Fax: (888) 555--1212"
  #     mark: 3
  #     author:
  #       - name: Montgomery Scott
  #   - name: Tyrell Inc.
  #     location: 123 Replicant Street, Los Angeles, USA 90210--4321
  #     mark: 4
  #     author:
  #       - name: Eldon Tyrell
  #         email: eldon@starfleet-academy.star
  #       - name: Roy Batty
  #         email: roy@replicant.offworld
keywords: ["Algorithmic Recourse", "Counterfactual Explanations", "Explainable AI", "Dynamic Systems"]
abstract: |
  Existing work on Counterfactual Explanations (CE) and Algorithmic Recourse (AR) has largely focused on single individuals in a static environment: given some estimated model, the goal is to find valid counterfactuals for an individual instance that fulfill various desiderata. The ability of such counterfactuals to handle dynamics like data and model drift remains a largely unexplored research challenge. There has also been surprisingly little work on the related question of how the actual implementation of recourse by one individual may affect other individuals. Through this work we aim to close that gap. We first show that many of the existing methodologies can be collectively described by a generalized framework. We then argue that the existing framework does not account for a hidden external cost of recourse, that only reveals itself when studying the endogenous dynamics of recourse at the group level. Through simulation experiments involving various state-of-the-art counterfactual generators and several benchmark datasets, we generate large numbers of counterfactuals and study the resulting domain and model shifts. We find that the induced shifts are substantial enough to likely impede the applicability of Algorithmic Recourse in some situations. Fortunately, we find various strategies to mitigate these concerns. Our simulation framework for studying recourse dynamics is fast and open-sourced. 

# use some specific Tex packages if needed. 
# with_ifpdf: true
with_cite: true
# amsmath need to be true to use with bookdown for referencing equations.
with_amsmath: true
# with_algorithmic: true
# with_array: true
# with_dblfloatfix: true

bibliography: ../bib.bib
csl: ieee.csl
output: 
  bookdown::pdf_book:
    keep_tex:  true
    base_format: rticles::ieee_article
    includes:
      in_header: "tex/preamble.tex"
      before_body: "tex/before_body.tex"
link-citations: true
#citation_sorting: none   ## used as sorting option of the biblatex package (if selected)
---

```{r, include=FALSE}
child_docs <- c(
  "sections/introduction.rmd",
  "sections/related.rmd",
  "sections/methodology.rmd",
  "sections/methodology_2.rmd",
  "sections/empirical.rmd",
  "sections/empirical_2.rmd",
  "sections/mitigation.rmd",
  "sections/discussion.rmd",
  "sections/limitations.rmd",
  "sections/conclusion.rmd"
)
knitr::opts_chunk$set(
  echo = FALSE,
  warning=FALSE,
  message=FALSE,
  fig.align = "center",
  out.width = "90%"
)
```

```{r, child=child_docs}
```

# References {.unnumbered}

::: {#refs}
:::

# Appendix

Granular results for all of our experiments can be found in this supplementary [appendix](https://anonymous.4open.science/r/AlgorithmicRecourseDynamics/build/dev/notebooks/appendix.html).
